// GET ALL CONTACTS
GET http://localhost:3000/contacts

### GET CONTACT BY ID

GET http://localhost:3000/contacts/643dcbf4f3a3b9b1c4e4f8a1

### RENDER CONNECTION TEST
GET https://cse341-contactsapi-o42n.onrender.com/contacts


 


